export const USER__LOGIN_SUCCESS = 'USER__LOGIN_SUCCESS';

export const USER__LOGOUT = 'USER__LOGOUT';

export const USER__SUBSCRIBE = 'USER__SUBSCRIBE';

export const USER__UNSUBSCRIBE = 'USER__UNSUBSCRIBE';

export const USER__GET_ANOTHER_USER_SUCCESS = 'SER__GET_ANOTHER_USER_SUCCESS';
